title: Rajani Nagaraju
logo: /assets/img/profile_pic.jpeg
description: <p> Technical architect with 10+ years experience in IoT Application development.Proficient in IoT architecture framework, MongoDB, MySQL, Kafka, Redis, Java and Stream analytics. Currently pursuing Executive PG in ML&AI from upGrad. </p>
theme: jekyll-theme-minimal
